import type { Category, Product, Order, OrderStatusHistory } from '@/types';

export const DEMO_MODE = !process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL === 'https://demo.supabase.co';

// globalThis를 사용해 Next.js dev 모드에서 모듈 재평가 시에도 데모 데이터 유지
const globalForDemo = globalThis as typeof globalThis & {
  __demoOrders?: Order[];
  __demoStatusHistory?: OrderStatusHistory[];
};

// ── Categories ──
export const demoCategories: Category[] = [
  { id: 'cat-1', slug: 'emergency', name: '오늘 큰일남', description: '생일, 기념일 깜빡했을 때', emoji: '🚨', display_order: 1, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-2', slug: 'gratitude', name: '고마운 사람', description: '감사한 마음을 꽃으로', emoji: '🙏', display_order: 2, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-3', slug: 'just_because', name: '괜히 보내봄', description: '이유 없이, 그냥', emoji: '🌸', display_order: 3, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-4', slug: 'celebration', name: '축하해줘야 함', description: '승진, 개업, 합격', emoji: '🎉', display_order: 4, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-5', slug: 'apology', name: '잘못했어요', description: '미안한 마음을 꽃으로', emoji: '😢', display_order: 5, is_active: true, created_at: new Date().toISOString() },
  { id: 'cat-6', slug: 'love', name: '사랑합니다', description: '사랑하는 사람에게', emoji: '💕', display_order: 6, is_active: true, created_at: new Date().toISOString() },
];

// ── Products ──
export const demoProducts: (Product & { category?: Category })[] = [
  {
    id: 'prod-1',
    category_id: 'cat-1',
    name: '긴급 구출 꽃다발',
    description: '깜빡한 기념일도 이 꽃이면 해결! 빨간 장미와 카네이션을 중심으로 풍성하게 구성한 꽃다발입니다.\n\n사랑하는 사람에게 진심을 전하세요.',
    short_description: '깜빡했어도 괜찮아, 이 꽃이면',
    price: 55000,
    sale_price: null,
    images: [],
    is_active: true,
    is_featured: true,
    flower_types: ['장미', '카네이션', '안개꽃'],
    size: 'M',
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[0],
  },
  {
    id: 'prod-2',
    category_id: 'cat-2',
    name: '감사 꽃바구니',
    description: '고마운 분에게 전하는 정성 가득 꽃바구니. 핑크 장미, 거베라, 리시안셔스로 따뜻한 마음을 담았습니다.',
    short_description: '고마운 마음, 꽃으로 전해요',
    price: 65000,
    sale_price: 58000,
    images: [],
    is_active: true,
    is_featured: true,
    flower_types: ['장미', '거베라', '리시안셔스'],
    size: 'L',
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[1],
  },
  {
    id: 'prod-3',
    category_id: 'cat-3',
    name: '괜히 보내는 미니 꽃다발',
    description: '이유 없이, 그냥 보내고 싶을 때. 부담 없는 사이즈의 러블리한 미니 꽃다발입니다.',
    short_description: '그냥, 네 생각이 나서',
    price: 35000,
    sale_price: null,
    images: [],
    is_active: true,
    is_featured: true,
    flower_types: ['튤립', '프리지아', '유칼립투스'],
    size: 'S',
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[2],
  },
  {
    id: 'prod-4',
    category_id: 'cat-4',
    name: '축하 대형 꽃다발',
    description: '승진, 개업, 합격! 특별한 날을 위한 대형 꽃다발. 화려한 백합과 장미의 조합으로 축하의 마음을 전합니다.',
    short_description: '축하하는 마음을 가득 담아',
    price: 85000,
    sale_price: 79000,
    images: [],
    is_active: true,
    is_featured: true,
    flower_types: ['백합', '장미', '수국', '델피니움'],
    size: 'XL',
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[3],
  },
  {
    id: 'prod-5',
    category_id: 'cat-5',
    name: '미안해 꽃다발',
    description: '말로 다 못한 미안한 마음을 꽃으로 전하세요. 부드러운 파스텔톤 장미와 유칼립투스로 구성했습니다.',
    short_description: '미안한 마음, 꽃이 대신 전해요',
    price: 48000,
    sale_price: null,
    images: [],
    is_active: true,
    is_featured: false,
    flower_types: ['장미', '유칼립투스', '라넌큘러스'],
    size: 'M',
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[4],
  },
  {
    id: 'prod-6',
    category_id: 'cat-6',
    name: '사랑의 빨간 장미 100송이',
    description: '특별한 사랑을 위한 빨간 장미 100송이. 프로포즈, 결혼기념일 등 잊지 못할 순간을 만들어드립니다.',
    short_description: '사랑한다는 말 대신',
    price: 150000,
    sale_price: 129000,
    images: [],
    is_active: true,
    is_featured: true,
    flower_types: ['빨간 장미'],
    size: 'XL',
    display_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[5],
  },
  {
    id: 'prod-7',
    category_id: 'cat-6',
    name: '러블리 핑크 부케',
    description: '핑크 장미와 작약으로 만든 로맨틱 부케. 연인에게 달콤한 마음을 전하세요.',
    short_description: '달콤한 핑크 사랑',
    price: 62000,
    sale_price: null,
    images: [],
    is_active: true,
    is_featured: false,
    flower_types: ['핑크 장미', '작약', '안개꽃'],
    size: 'M',
    display_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[5],
  },
  {
    id: 'prod-8',
    category_id: 'cat-2',
    name: '플로리스트 추천 꽃다발',
    description: '뭘 골라야 할지 모르겠다면 플로리스트에게 맡겨주세요! 당일 가장 싱싱한 꽃으로 아름답게 만들어 드립니다.',
    short_description: '플로리스트가 정성껏 골라요',
    price: 55000,
    sale_price: null,
    images: [],
    is_active: true,
    is_featured: true,
    flower_types: ['시즌 꽃'],
    size: 'M',
    display_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: demoCategories[1],
  },
];

// ── Demo Orders (상태별 3건씩, 총 18건) ──
const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const todayNum = today.replace(/-/g, '');
const yesterdayNum = yesterday.replace(/-/g, '');

const _initialOrders: Order[] = [
  // ── Pending (접수 대기, 결제 전) ×3 ──
  {
    id: 'order-p1', order_number: `BU-${todayNum}-0001`,
    sender_name: '김태현', sender_phone: '01011110001',
    recipient_name: '김어머니', recipient_phone: '01022220001',
    recipient_address: '부산시 해운대구 마린시티2로 33', recipient_address_detail: '해운대자이 1503호', recipient_zipcode: '48120',
    product_id: 'prod-1', product_name: '긴급 구출 꽃다발', product_price: 55000, quantity: 1,
    status: 'pending', card_message: '엄마 생신 축하드려요!', delivery_date: today, delivery_time_slot: 'afternoon',
    special_instructions: '', subtotal: 55000, delivery_fee: 0, total_amount: 55000,
    payment_status: 'pending', payment_id: null, paid_at: null, partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'order-p2', order_number: `BU-${todayNum}-0002`,
    sender_name: '이수빈', sender_phone: '01011110002',
    recipient_name: '박지연', recipient_phone: '01022220002',
    recipient_address: '부산시 수영구 광안해변로 219', recipient_address_detail: '광안리더샵 803호', recipient_zipcode: '48310',
    product_id: 'prod-3', product_name: '괜히 보내는 미니 꽃다발', product_price: 35000, quantity: 1,
    status: 'pending', card_message: '', delivery_date: today, delivery_time_slot: 'anytime',
    special_instructions: '문 앞에 놓아주세요', subtotal: 35000, delivery_fee: 0, total_amount: 35000,
    payment_status: 'pending', payment_id: null, paid_at: null, partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'order-p3', order_number: `BU-${todayNum}-0003`,
    sender_name: '최준서', sender_phone: '01011110003',
    recipient_name: '한소희', recipient_phone: '01022220003',
    recipient_address: '부산시 남구 용호로 120', recipient_address_detail: '', recipient_zipcode: '48500',
    product_id: 'prod-7', product_name: '러블리 핑크 부케', product_price: 62000, quantity: 1,
    status: 'pending', card_message: '사랑해 💕', delivery_date: today, delivery_time_slot: 'morning',
    special_instructions: '', subtotal: 62000, delivery_fee: 0, total_amount: 62000,
    payment_status: 'pending', payment_id: null, paid_at: null, partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },

  // ── Confirmed (접수 완료, 결제 완료) ×3 ──
  {
    id: 'order-c1', order_number: `BU-${todayNum}-0004`,
    sender_name: '김지수', sender_phone: '01012345678',
    recipient_name: '이미경', recipient_phone: '01087654321',
    recipient_address: '부산시 해운대구 센텀남대로 35', recipient_address_detail: '센텀시티 A동 1201호', recipient_zipcode: '48058',
    product_id: 'prod-1', product_name: '긴급 구출 꽃다발', product_price: 55000, quantity: 1,
    status: 'confirmed', card_message: '생일 축하해! 항상 고마워 💐', delivery_date: today, delivery_time_slot: 'afternoon',
    special_instructions: '문 앞에 놓아주세요', subtotal: 55000, delivery_fee: 0, total_amount: 55000,
    payment_status: 'paid', payment_id: 'demo-pay-c1', paid_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'order-c2', order_number: `BU-${todayNum}-0005`,
    sender_name: '오민재', sender_phone: '01033330001',
    recipient_name: '오아버지', recipient_phone: '01044440001',
    recipient_address: '부산시 동래구 온천장로 55', recipient_address_detail: '래미안 1102호', recipient_zipcode: '47710',
    product_id: 'prod-2', product_name: '감사 꽃바구니', product_price: 58000, quantity: 1,
    status: 'confirmed', card_message: '아버지 항상 감사합니다 🙏', delivery_date: today, delivery_time_slot: 'anytime',
    special_instructions: '경비실에 맡겨주세요', subtotal: 58000, delivery_fee: 0, total_amount: 58000,
    payment_status: 'paid', payment_id: 'demo-pay-c2', paid_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 95 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'order-c3', order_number: `BU-${todayNum}-0006`,
    sender_name: '장서윤', sender_phone: '01033330002',
    recipient_name: '김동현', recipient_phone: '01044440002',
    recipient_address: '부산시 부산진구 중앙대로 680', recipient_address_detail: '서면 오피스텔 407호', recipient_zipcode: '47240',
    product_id: 'prod-4', product_name: '축하 대형 꽃다발', product_price: 79000, quantity: 1,
    status: 'confirmed', card_message: '승진 축하해요!! 🎉', delivery_date: today, delivery_time_slot: 'afternoon',
    special_instructions: '', subtotal: 79000, delivery_fee: 0, total_amount: 79000,
    payment_status: 'paid', payment_id: 'demo-pay-c3', paid_at: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 85 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },

  // ── Preparing (준비중) ×3 ──
  {
    id: 'order-r1', order_number: `BU-${todayNum}-0007`,
    sender_name: '박준호', sender_phone: '01098765432',
    recipient_name: '최수진', recipient_phone: '01011112222',
    recipient_address: '부산시 수영구 광안해변로 100', recipient_address_detail: '광안리뷰 오피스텔 502호', recipient_zipcode: '48310',
    product_id: 'prod-6', product_name: '사랑의 빨간 장미 100송이', product_price: 129000, quantity: 1,
    status: 'preparing', card_message: '1주년 축하해 ❤️ 사랑해', delivery_date: today, delivery_time_slot: 'morning',
    special_instructions: '', subtotal: 129000, delivery_fee: 0, total_amount: 129000,
    payment_status: 'paid', payment_id: 'demo-pay-r1', paid_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 70 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'order-r2', order_number: `BU-${todayNum}-0008`,
    sender_name: '윤하은', sender_phone: '01055550001',
    recipient_name: '송미래', recipient_phone: '01066660001',
    recipient_address: '부산시 금정구 부산대학로 63', recipient_address_detail: '부산대 정문 앞', recipient_zipcode: '46241',
    product_id: 'prod-3', product_name: '괜히 보내는 미니 꽃다발', product_price: 35000, quantity: 1,
    status: 'preparing', card_message: '힘내! 응원해 🌸', delivery_date: today, delivery_time_slot: 'afternoon',
    special_instructions: '정문 카페 앞에서 전달 부탁드려요', subtotal: 35000, delivery_fee: 0, total_amount: 35000,
    payment_status: 'paid', payment_id: 'demo-pay-r2', paid_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'order-r3', order_number: `BU-${todayNum}-0009`,
    sender_name: '강민수', sender_phone: '01055550002',
    recipient_name: '강어머니', recipient_phone: '01066660002',
    recipient_address: '부산시 사하구 낙동남로 1381', recipient_address_detail: '하단 주공 3단지 205동 801호', recipient_zipcode: '49324',
    product_id: 'prod-8', product_name: '플로리스트 추천 꽃다발', product_price: 55000, quantity: 1,
    status: 'preparing', card_message: '엄마 감사해요 항상 건강하세요', delivery_date: today, delivery_time_slot: 'anytime',
    special_instructions: '', subtotal: 55000, delivery_fee: 0, total_amount: 55000,
    payment_status: 'paid', payment_id: 'demo-pay-r3', paid_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 48 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },

  // ── Delivering (배송중) ×3 ──
  {
    id: 'order-d1', order_number: `BU-${todayNum}-0010`,
    sender_name: '정민아', sender_phone: '01033334444',
    recipient_name: '정어머니', recipient_phone: '01055556666',
    recipient_address: '부산시 사직동 사직로 45', recipient_address_detail: '', recipient_zipcode: '47000',
    product_id: 'prod-2', product_name: '감사 꽃바구니', product_price: 58000, quantity: 1,
    status: 'delivering', card_message: '엄마 항상 감사합니다 🙏', delivery_date: today, delivery_time_slot: 'anytime',
    special_instructions: '벨 누르지 말고 문 앞에 놓아주세요', subtotal: 58000, delivery_fee: 0, total_amount: 58000,
    payment_status: 'paid', payment_id: 'demo-pay-d1', paid_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'order-d2', order_number: `BU-${todayNum}-0011`,
    sender_name: '백승우', sender_phone: '01077770001',
    recipient_name: '이지원', recipient_phone: '01088880001',
    recipient_address: '부산시 연제구 중앙대로 1001', recipient_address_detail: '연산동 럭키 오피스텔 1201호', recipient_zipcode: '47588',
    product_id: 'prod-5', product_name: '미안해 꽃다발', product_price: 48000, quantity: 1,
    status: 'delivering', card_message: '어제 미안했어. 화해하자 😢', delivery_date: today, delivery_time_slot: 'afternoon',
    special_instructions: '', subtotal: 48000, delivery_fee: 0, total_amount: 48000,
    payment_status: 'paid', payment_id: 'demo-pay-d2', paid_at: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'order-d3', order_number: `BU-${todayNum}-0012`,
    sender_name: '서지훈', sender_phone: '01077770002',
    recipient_name: '노은비', recipient_phone: '01088880002',
    recipient_address: '부산시 기장군 기장읍 기장해안로 216', recipient_address_detail: '', recipient_zipcode: '46044',
    product_id: 'prod-4', product_name: '축하 대형 꽃다발', product_price: 79000, quantity: 1,
    status: 'delivering', card_message: '결혼 축하해! 행복해라 🎉', delivery_date: today, delivery_time_slot: 'morning',
    special_instructions: '카페 앞에서 전달 부탁해요', subtotal: 79000, delivery_fee: 0, total_amount: 79000,
    payment_status: 'paid', payment_id: 'demo-pay-d3', paid_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(), updated_at: new Date().toISOString(),
  },

  // ── Delivered (배송 완료) ×3 ──
  {
    id: 'order-v1', order_number: `BU-${yesterdayNum}-0001`,
    sender_name: '임채영', sender_phone: '01099990001',
    recipient_name: '임아버지', recipient_phone: '01000010001',
    recipient_address: '부산시 중구 중앙대로 2', recipient_address_detail: '부산역 인근 오피스텔 302호', recipient_zipcode: '48943',
    product_id: 'prod-1', product_name: '긴급 구출 꽃다발', product_price: 55000, quantity: 1,
    status: 'delivered', card_message: '아빠 생신 축하드립니다!', delivery_date: yesterday, delivery_time_slot: 'afternoon',
    special_instructions: '', subtotal: 55000, delivery_fee: 0, total_amount: 55000,
    payment_status: 'paid', payment_id: 'demo-pay-v1', paid_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-v2', order_number: `BU-${yesterdayNum}-0002`,
    sender_name: '고은서', sender_phone: '01099990002',
    recipient_name: '류현진', recipient_phone: '01000010002',
    recipient_address: '부산시 강서구 녹산산단 335로 7', recipient_address_detail: '', recipient_zipcode: '46757',
    product_id: 'prod-6', product_name: '사랑의 빨간 장미 100송이', product_price: 129000, quantity: 1,
    status: 'delivered', card_message: '프로포즈 성공! 사랑해 ❤️', delivery_date: yesterday, delivery_time_slot: 'morning',
    special_instructions: '12시 정각에 전달해주세요', subtotal: 129000, delivery_fee: 0, total_amount: 129000,
    payment_status: 'paid', payment_id: 'demo-pay-v2', paid_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-v3', order_number: `BU-${yesterdayNum}-0003`,
    sender_name: '문재호', sender_phone: '01099990003',
    recipient_name: '문어머니', recipient_phone: '01000010003',
    recipient_address: '부산시 북구 화명동 롯데캐슬 카이저', recipient_address_detail: '103동 2202호', recipient_zipcode: '46507',
    product_id: 'prod-8', product_name: '플로리스트 추천 꽃다발', product_price: 55000, quantity: 1,
    status: 'delivered', card_message: '어머니 항상 건강하세요', delivery_date: yesterday, delivery_time_slot: 'anytime',
    special_instructions: '', subtotal: 55000, delivery_fee: 0, total_amount: 55000,
    payment_status: 'paid', payment_id: 'demo-pay-v3', paid_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: null, cancel_reason: null,
    created_at: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
  },

  // ── Cancelled (취소) ×3 ──
  {
    id: 'order-x1', order_number: `BU-${yesterdayNum}-0004`,
    sender_name: '신유진', sender_phone: '01000020001',
    recipient_name: '신동생', recipient_phone: '01000030001',
    recipient_address: '부산시 해운대구 좌동 123', recipient_address_detail: '', recipient_zipcode: '48090',
    product_id: 'prod-3', product_name: '괜히 보내는 미니 꽃다발', product_price: 35000, quantity: 1,
    status: 'cancelled', card_message: '', delivery_date: yesterday, delivery_time_slot: 'anytime',
    special_instructions: '', subtotal: 35000, delivery_fee: 0, total_amount: 35000,
    payment_status: 'refunded', payment_id: 'demo-pay-x1', paid_at: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(), cancel_reason: '고객 요청 취소',
    created_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-x2', order_number: `BU-${yesterdayNum}-0005`,
    sender_name: '한지민', sender_phone: '01000020002',
    recipient_name: '조은별', recipient_phone: '01000030002',
    recipient_address: '부산시 동구 초량동 1200-5', recipient_address_detail: '', recipient_zipcode: '48796',
    product_id: 'prod-5', product_name: '미안해 꽃다발', product_price: 48000, quantity: 1,
    status: 'cancelled', card_message: '미안해...', delivery_date: yesterday, delivery_time_slot: 'afternoon',
    special_instructions: '', subtotal: 48000, delivery_fee: 0, total_amount: 48000,
    payment_status: 'refunded', payment_id: 'demo-pay-x2', paid_at: new Date(Date.now() - 29 * 60 * 60 * 1000).toISOString(),
    partner_shop: null, cancelled_at: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(), cancel_reason: '주소 오류',
    created_at: new Date(Date.now() - 31 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-x3', order_number: `BU-${todayNum}-0013`,
    sender_name: '권도영', sender_phone: '01000020003',
    recipient_name: '이채원', recipient_phone: '01000030003',
    recipient_address: '부산시 사상구 학감대로 272', recipient_address_detail: '사상역 인근', recipient_zipcode: '46978',
    product_id: 'prod-7', product_name: '러블리 핑크 부케', product_price: 62000, quantity: 1,
    status: 'cancelled', card_message: '사랑해', delivery_date: today, delivery_time_slot: 'morning',
    special_instructions: '', subtotal: 62000, delivery_fee: 0, total_amount: 62000,
    payment_status: 'pending', payment_id: null, paid_at: null,
    partner_shop: null, cancelled_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(), cancel_reason: '고객 변심',
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

const _initialStatusHistory: OrderStatusHistory[] = [
  // pending orders
  { id: 'h-p1', order_id: 'order-p1', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
  { id: 'h-p2', order_id: 'order-p2', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString() },
  { id: 'h-p3', order_id: 'order-p3', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 1 * 60 * 1000).toISOString() },
  // confirmed orders
  { id: 'h-c1a', order_id: 'order-c1', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
  { id: 'h-c1b', order_id: 'order-c1', status: 'confirmed', note: '결제 완료', created_at: new Date(Date.now() - 115 * 60 * 1000).toISOString() },
  { id: 'h-c2a', order_id: 'order-c2', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 95 * 60 * 1000).toISOString() },
  { id: 'h-c2b', order_id: 'order-c2', status: 'confirmed', note: '결제 완료', created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString() },
  { id: 'h-c3a', order_id: 'order-c3', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 85 * 60 * 1000).toISOString() },
  { id: 'h-c3b', order_id: 'order-c3', status: 'confirmed', note: '결제 완료', created_at: new Date(Date.now() - 80 * 60 * 1000).toISOString() },
  // preparing orders
  { id: 'h-r1a', order_id: 'order-r1', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 70 * 60 * 1000).toISOString() },
  { id: 'h-r1b', order_id: 'order-r1', status: 'confirmed', note: '결제 완료', created_at: new Date(Date.now() - 65 * 60 * 1000).toISOString() },
  { id: 'h-r1c', order_id: 'order-r1', status: 'preparing', note: '꽃 준비 시작', created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString() },
  { id: 'h-r2a', order_id: 'order-r2', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString() },
  { id: 'h-r2b', order_id: 'order-r2', status: 'confirmed', note: '결제 완료', created_at: new Date(Date.now() - 50 * 60 * 1000).toISOString() },
  { id: 'h-r2c', order_id: 'order-r2', status: 'preparing', note: '꽃 준비 시작', created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  // delivering orders
  { id: 'h-d1a', order_id: 'order-d1', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString() },
  { id: 'h-d1b', order_id: 'order-d1', status: 'confirmed', note: '결제 완료', created_at: new Date(Date.now() - 2.4 * 60 * 60 * 1000).toISOString() },
  { id: 'h-d1c', order_id: 'order-d1', status: 'preparing', note: '꽃 준비 시작', created_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString() },
  { id: 'h-d1d', order_id: 'order-d1', status: 'delivering', note: '배송 출발', created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  // cancelled order
  { id: 'h-x1a', order_id: 'order-x1', status: 'pending', note: '주문 생성', created_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString() },
  { id: 'h-x1b', order_id: 'order-x1', status: 'confirmed', note: '결제 완료', created_at: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString() },
  { id: 'h-x1c', order_id: 'order-x1', status: 'cancelled', note: '고객 요청 취소', created_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString() },
];

// globalThis에 캐싱하여 Next.js dev 모듈 재평가에도 상태 유지
if (!globalForDemo.__demoOrders) {
  globalForDemo.__demoOrders = _initialOrders;
}
if (!globalForDemo.__demoStatusHistory) {
  globalForDemo.__demoStatusHistory = _initialStatusHistory;
}

export const demoOrders = globalForDemo.__demoOrders;
export const demoStatusHistory = globalForDemo.__demoStatusHistory;
